# Tiny configuration that will not produce any sensible results, but should compile quickly and help with debugging

physical:
  name: H2

optimization:
  n_epochs: 2
  optimizer:
    name: "adam"
  batch_size: 32

evaluation:
  n_epochs: 2

model:
  net_width: 4
  net_depth: 0
  embedding:
    net_width: 4
    net_depth: 0
    embedding_dim: 5
  baseline:
    n_determinants: 1

mcmc:
  n_burn_in_opt: 2
  n_burn_in_eval: 2
  n_walkers_opt: 64

computation:
  disable_jit: False # Set to true, to disable JIT-compilation, helping with debugging
