computation:
  disable_jit: False

physical:
  name: Li

pre_training:
  n_epochs: 1000
  optimizer:
    name: adam
  learning_rate: 3e-4
  use_only_leading_determinant: True

model:
  baseline:
    n_determinants: 16

optimization:
  batch_size: 256

mcmc:
  n_walkers_opt: 256
  n_burn_in_opt: 1
  n_burn_in_eval: 1
  stepsize_update_interval: 500

