experiment_name: debug_intermedeval

physical:
  name: LiH

optimization:
  n_epochs: 100
  checkpoints:
    keep_every_n_epochs: 20
  mcmc:
    n_walkers: 50
    n_inter_steps: 1
    n_burn_in: 0
  optimizer:
    name: kfac_adam

evaluation:
  n_epochs: 20
  mcmc:
    n_walkers: 50
    n_inter_steps: 1
    n_burn_in: 0

pre_training:
  n_epochs: 50
  mcmc:
    n_walkers: 100
    n_burn_in: 5

model:
  name: dpe4
  embedding:
    n_iterations: 2
    n_hidden_one_el: 10
    n_hidden_two_el: 5
  orbitals:
    baseline_orbitals:
      use_bf_shift: true
  jastrow:
    n_determinants: 2

#logging:
#  wandb:
#    entity: schroedinger_univie
#    project: debug

computation:
  require_gpu: false
  disable_jit: false
  n_devices: 2
  force_device_count: True