physical:
  name: B

model:
  orbitals:
    use_full_det: false
    baseline_orbitals:
      baseline:
        name: casscf
      use_bf_factor: false
      use_bf_shift: false
    envelope_orbitals:
    n_determinants: 4
  use_jastrow: false
  use_el_el_cusp_correction: false
  embedding:

mcmc:
  n_walkers_opt: 20
  n_walkers_eval: 20

pre_training:
  n_epochs: 0

optimization:
  batch_size: 20
  n_epochs: 0

evaluation:
  n_epochs: 10_000

#logging:
#  wandb:
#    entity: schroedinger_univie
#    project: eval_baseline
#
