experiment_name: dpe
physical:
  R: [[0,0,0]]
  Z: [5]
  n_electrons: 5
  n_cas_electrons: 3
  n_cas_orbitals: 2
  n_up: 3

pre_training:
  use: true
  n_epochs: 0
  baseline:
    basis_set: default:6-31G__H:6-31G**

optimization:
  mcmc:
    n_walkers: 2048
  n_epochs: 10
  checkpoints:
    replace_every_n_epochs: 2
    keep_every_n_epochs: 5

evaluation:
  n_epochs: 0

model:
  orbitals:
    n_determinants: 2
  name: dpe4 # paulinet必须要casscf组态个数与n_determinants相等

logging:
  tags: []
  log_opt_state: true
  basic:
    n_skip_epochs: 0
    log_to_stdout: true
    log_level: INFO
    fname: log.out