# 1) Set the following in the wandb-sweep-UI
command:
- dpe_sweep_agent
method: bayes
metric:
  goal: minimize
  name: error_plus_2_stdev
parameters:
  optimization.learning_rate:
    distribution: log_uniform
    max: -9.2
    min: -11.5
  optimization.optimizer.momentum:
    max: 0.6
    min: 0
  # Add more parameters as required...


# 2) Launch agents for the sweep with: deeperwin --wandb-sweep schroedinger_univie/kfac_adam_sweep/qn6aqmo9 nr_of_agents nr_of_runs_per_agent config.yml

