# Basic configuration using default settings
physical:
  name: C # alternatives: Be, B, C, O, F, Ne, LiH

optimization:
  optimizer:
    name: adam # alternatives: kfac, slbfgs
    learning_rate: 1.5e-3 # Usually works well for adam and slbfgs; use 5e-5 for KFAC

# Uncomment to log to your W&B account; requires that you stored your api-key using 'wandb login'
#logging:
#  wandb:
#    entity: <your wandb username or team name>
#    project: <wandb project name>


